<a href="https://colab.research.google.com/github/11249a150-art/SCSVMV_LABS/blob/main/11249A150.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Start with mixed values
num_val <- 123.45
char_val <- "456"
log_val <- TRUE
# Numeric conversions
as.integer(num_val)
# 123 (truncates decimal)
as.character(num_val)  # "123.45"
as.numeric(char_val)
# 456
# Character conversions
as.numeric(char_val)
as.integer("123")
as.logical("TRUE")
# Logical conversions
as.numeric(log_val)
# 456
# 123
# TRUE
# 1 (TRUE=1, FALSE=0)
as.character(log_val)  # "TRUE"

[1] 123

[1] "123.45"

[1] 456

[1] 456

[1] 123

[1] TRUE

[1] 1

[1] "TRUE"

In [ ]:
num_var <- 42.5
cat("Numeric variable value:", num_var, "\n")
cat("Numeric variable type:", class(num_var), "\n\n")

Numeric variable value: 42.5
Numeric variable type: numeric

In [ ]:
int_var <- as.integer(100)
cat("Integer variable value:", int_var, "\n")
cat("Integer variable type:", class(int_var), "\n\n")

Integer variable value: 100
Integer variable type: integer

In [ ]:
# Character variable
char_var <- "Tambaram"
cat("Character variable value:", char_var, "\n")
cat("Character variable type:", class(char_var), "\n\n")

Character variable value: Tambaram
Character variable type: character

In [ ]:
# Logical variable
log_var <- TRUE
cat("Logical variable value:", log_var, "\n")
cat("Logical variable type:", class(log_var), "\n\n")

In [ ]:
# Complex variable (bonus example)
comp_var <- 1 + 2i
cat("Complex variable value:", comp_var, "\n")
cat("Complex variable type:", class(comp_var), "\n")

Complex variable value: 1+2i
Complex variable type: complex

In [ ]:
mat <- matrix(1:12,ncol=4, nrow=3)  # 3x4 matrix, fills column-wise
print(mat)

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12

In [ ]:
my_list <- list(
 name = "Tirupati",
 age = 25,
 coords = c(13.62, 79.41),
 active = TRUE
)
str(my_list)  # Shows structure

List of 4
 $ name  : chr "Tirupati"
 $ age   : num 25
 $ coords: num [1:2] 13.6 79.4
 $ active: logi TRUE

In [ ]:
# 2. Structures
vec <- c(1,2,3)
mat <- matrix(1:6, nrow=2)
lst <- list(city="Tambaram", temp=28.5)
df <- data.frame(id=1:2, score=c(85,92))
cat("Vector:", vec, "\n")
cat("Matrix:\n"); print(mat)
cat("List:\n"); print(lst)
cat("Data frame:\n"); print(df)

Vector: 1 2 3
Matrix:
     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6
List:
$city
[1] "Tambaram"

$temp
[1] 28.5

Data frame:
  id score
1  1    85
2  2    92

In [ ]:
# 1. Type conversions
num <- 123.45
cat("Original:", num, class(num), "\n")
cat("To integer:", as.integer(num), "\n")
cat("To character:", as.character(num), "\n\n")
Original: 123.45 numeric
To integer: 123
To character: 123.45

ERROR: Error in parse(text = input): <text>:6:18: unexpected symbol
5: cat("To character:", as.character(num), "\n\n")
6: Original: 123.45 numeric
                    ^

In [ ]:
# 3. Conversions between structures
cat("Matrix to vector:", as.vector(mat), "\n")
cat("List to data frame:\n"); print(as.data.frame(lst))

Matrix to vector: 1 2 3 4 5 6
List to data frame:
      city temp
1 Tambaram 28.5

In [ ]:
cat("=== R ARITHMETIC OPERATORS DEMO ===\n\n")
# Define sample values
a <- 15
b <- 4
cat("Values: a =", a, ", b =", b, "\n\n")
# 1. Basic Arithmetic
cat("1. BASIC OPERATIONS:\n")
cat("Addition (+):     ", a + b, "\n")
cat("Subtraction (-):  ", a - b, "\n")
cat("Multiplication (*):", a * b, "\n")
cat("Division (/):     ", a / b, "\n")
cat("Power (^):        2^3 =", 2^3, "\n\n")

=== R ARITHMETIC OPERATORS DEMO ===

Values: a = 15 , b = 4

1. BASIC OPERATIONS:
Addition (+):      19
Subtraction (-):   11
Multiplication (*): 60
Division (/):      3.75
Power (^):        2^3 = 8

In [ ]:
# 2. Special Division Operators
cat("2. DIVISION OPERATORS:\n")
cat("Modulo (%%):      ", a %% b, " (remainder)\n")
cat("Integer Div (%/%):", a %/% b, " (drops decimal)\n")
cat("Normal Div (/):   ", a / b, " (3.75)\n\n")

2. DIVISION OPERATORS:
Modulo (%%):       3  (remainder)
Integer Div (%/%): 3  (drops decimal)
Normal Div (/):    3.75  (3.75)

In [ ]:
# 3. Vector Operations (Element-wise)
cat("3. VECTOR ARITHMETIC:\n")
x <- c(10, 20, 30)
y <- c(2, 4, 5)
cat("Vector x:", x, "\n")
cat("Vector y:", y, "\n")
cat("x + y:   ", x + y, "\n")
cat("x * y:   ", x * y, "\n")
cat("x / y:   ", x / y, "\n\n")

3. VECTOR ARITHMETIC:
Vector x: 10 20 30
Vector y: 2 4 5
x + y:    12 24 35
x * y:    20 80 150
x / y:    5 5 6

In [ ]:
# 4. Real-World Example: Rectangle Area
length <- 12.5
width <- 8.2
area <- length * width
cat("4. RECTANGLE AREA:\n")
cat("Length =", length, ", Width =", width, "\n")
cat("Area =", area, "\n\n")

4. RECTANGLE AREA:
Length = 12.5 , Width = 8.2
Area = 102.5

In [ ]:
# 5. Image Processing Example (Pixel Math)
cat("5. IMAGE PIXEL EXAMPLE:\n")
r <- 255
# Red channel
g <- 128
b <- 64
# Green channel
# Blue channel
brightness <- (r + g + b) / 3
cat("RGB values: R=", r, "G=", g, "B=", b, "\n")
cat("Average brightness:", round(brightness), "\n")

5. IMAGE PIXEL EXAMPLE:
RGB values: R= 255 G= 128 B= 64
Average brightness: 149

In [ ]:
# 5. Image Processing Example (Pixel Math)
cat("5. IMAGE PIXEL EXAMPLE:\n")
r <- 255
# Red channel
g <- 128
b <- 64
# Green channel
# Blue channel
brightness <- (r + g + b) / 3
cat("RGB values: R=", r, "G=", g, "B=", b, "\n")
cat("Average brightness:", round(brightness), "\n")

5. IMAGE PIXEL EXAMPLE:
RGB values: R= 255 G= 128 B= 64
Average brightness: 149

In [ ]:
# 2. Vector Comparisons (Element-wise)
cat("2. VECTOR COMPARISONS:\n")
x <- c(10, 20, 30, 25)
y <- c(15, 20, 25, 30)
cat("Vector x:", x, "\n")
cat("Vector y:", y, "\n")
cat("x == y:    ", x == y, "\n")
cat("x > y:     ", x > y, "\n")
cat("x >= y:    ", x >= y, "\n")
cat("x <= y:    ", x <= y, "\n\n")

In [ ]:
# 3. String Comparisons
cat("3. CHARACTER COMPARISONS:\n")
place1 <- "Tirupati"
place2 <- "Tambaram"
place3 <- "Tirupati"
cat("place1 == place3: ", place1 == place3, "\n")
cat("place1 != place2: ", place1 != place2, "\n\n")

3. CHARACTER COMPARISONS:
place1 == place3:  TRUE
place1 != place2:  TRUE

In [ ]:
# 4. Practical Example: Student Grade Filter
cat("4. STUDENT GRADES FILTER:\n")
scores <- c(85, 72, 95, 68, 88)
pass_threshold <- 75
failed <- scores < pass_threshold
cat("Scores:", scores, "\n")
cat("Pass threshold:", pass_threshold, "\n")
cat("Failed students (scores < 75):", failed, "\n")
cat("Number failed:", sum(failed), "\n\n")

In [ ]:
# 5. Image Thresholding Example (Vision Relevant)
cat("5. IMAGE THRESHOLDING:\n")
pixel_values <- c(50, 120, 200, 80, 250)
threshold <- 100
bright_pixels <- pixel_values > threshold
cat("Pixel values:", pixel_values, "\n")
cat("Bright pixels (>100):", bright_pixels, "\n")
cat("Count of bright pixels:", sum(bright_pixels), "\n")

5. IMAGE THRESHOLDING:
Pixel values: 50 120 200 80 250
Bright pixels (>100): FALSE TRUE TRUE FALSE TRUE
Count of bright pixels: 3

In [ ]:
# 1. Scalar Logical Values
cat("1. SCALAR LOGICALS:\n")
p <- TRUE
q <- FALSE
cat("p =", p, ", q =", q, "\n")
cat("p & q (AND):     ", p & q, "\n")
cat("p && q (AND):    ", p && q, "\n")
cat("p | q (OR):      ", p | q, "\n")
cat("p || q (OR):     ", p || q, "\n")
cat("!p (NOT p):      ", !p, "\n")
cat("!q (NOT q):      ", !q, "\n\n")

1. SCALAR LOGICALS:
p = TRUE , q = FALSE
p & q (AND):      FALSE
p && q (AND):     FALSE
p | q (OR):       TRUE
p || q (OR):      TRUE
!p (NOT p):       FALSE
!q (NOT q):       TRUE

In [ ]:
# 2. From Comparisons
cat("2. FROM COMPARISONS:\n")
a <- 25
b <- 18
c <- 30
cat("a =", a, ", b =", b, ", c =", c, "\n")
cat("(a > b) & (b < c):", (a > b) & (b < c), "\n")
cat("(a > b) && (b < c):", (a > b) && (b < c), "\n")
cat("(a < b) | (c > b):", (a < b) | (c > b), "\n\n")

2. FROM COMPARISONS:
a = 25 , b = 18 , c = 30
(a > b) & (b < c): TRUE
(a > b) && (b < c): TRUE
(a < b) | (c > b): TRUE

In [ ]:
# 3. Vector Logical Operations (Element-wise)
cat("3. VECTOR LOGICALS (& and | are VECTORIZED):\n")
x <- c(TRUE, FALSE, TRUE, FALSE)
y <- c(FALSE, TRUE, TRUE, FALSE)
cat("Vector x:", x, "\n")
cat("Vector y:", y, "\n")
cat("x & y: ", x & y, "\n")
cat("x | y: ", x | y, "\n")
cat("!(x):  ", !x, "\n\n")

3. VECTOR LOGICALS (& and | are VECTORIZED):
Vector x: TRUE FALSE TRUE FALSE
Vector y: FALSE TRUE TRUE FALSE
x & y:  FALSE FALSE TRUE FALSE
x | y:  TRUE TRUE TRUE FALSE
!(x):   FALSE TRUE FALSE TRUE

In [ ]:
# 4. Practical Example: Student Eligibility Filter
cat("4. STUDENT ELIGIBILITY:\n")
scores <- c(85, 72, 95, 68, 88)
attendance <- c(95, 82, 98, 60, 90)  # percent
min_score <- 75
min_attend <- 80
eligible <- (scores >= min_score) & (attendance >= min_attend)
cat("Scores:", scores, "\n")
cat("Attendance:", attendance, "\n")
cat("Eligible:", eligible, "\n")
cat("Eligible count:", sum(eligible), "out of", length(eligible), "\n\n")

4. STUDENT ELIGIBILITY:
Scores: 85 72 95 68 88
Attendance: 95 82 98 60 90
Eligible: TRUE FALSE TRUE FALSE TRUE
Eligible count: 3 out of 5

In [ ]:
# 5. Image Processing: Multi-Condition Mask
cat("5. IMAGE MASKING (Vision Example):\n")
is_bright <- c(TRUE, FALSE, TRUE, FALSE, TRUE)  # brightness > threshold
is_edge <- c(FALSE, TRUE, TRUE, FALSE, TRUE)
# edge detected
valid_pixels <- is_bright & is_edge
cat("Bright pixels:", is_bright, "\n")
cat("Edge pixels:  ", is_edge, "\n")
cat("Valid pixels: ", valid_pixels, "\n")
cat("Valid count:  ", sum(valid_pixels), "\n")

5. IMAGE MASKING (Vision Example):
Bright pixels: TRUE FALSE TRUE FALSE TRUE
Edge pixels:   FALSE TRUE TRUE FALSE TRUE
Valid pixels:  FALSE FALSE TRUE FALSE TRUE
Valid count:   2

In [ ]:
for (i in 1:5) {
  print(i)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5

In [ ]:
fruits <- c("apple", "banana", "mango")
for (fruit in fruits) {
  print(fruit)
}

[1] "apple"
[1] "banana"
[1] "mango"

In [ ]:
x <- 1
while (x <= 5) {
  print(x)
  x <- x + 1
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5

In [ ]:
x <- 1
repeat {
  print(x)
  x <- x + 1
if (x > 5) {
break
  }
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5

In [ ]:
for (i in 1:10) {
if (i == 5) {
break
  }
  print(i)
}

[1] 1
[1] 2
[1] 3
[1] 4

In [ ]:
for (i in 1:5) {
if (i == 3) {
next
  }
  print(i)
}

[1] 1
[1] 2
[1] 4
[1] 5

In [ ]:
roll_no <- 101 # Integer
name <- "Anitha" # Character
cgpa <- 8.45 # Numeric
pass <- TRUE # Logical
roll_no
name
cgpa
pass

[1] 101

[1] "Anitha"

[1] 8.45

[1] TRUE

In [ ]:
emp_id <- 5001
salary <- 45000.75
department <- "IT"
is_permanent <- TRUE
emp_id
salary
department
is_permanent

In [ ]:
product_name <- "Laptop"
price <- 55000
stock_available <- 25
discount_eligible <- FALSE
product_name
price
stock_available
discount_eligible

In [ ]:
city <- "Chennai"
temperature <- 36.5
rain <- FALSE
wind_speed <- 12.8
city
temperature
rain
wind_speed

In [ ]:
subject <- "Mathematics"
total_marks <- 100
marks_obtained <- 78
result <- marks_obtained >= 40
subject
total_marks
marks_obtained
result

In [ ]:
age <- 25
income <- 35000
if(age > 21 & income > 30000){
print("Eligible for Loan")
} else {
print("Not Eligible for Loan")
}

In [ ]:
attendance <- 78
if(attendance >= 75){
print("Eligible for Exam")
} else {
print("Not Eligible for Exam")
}

In [ ]:
amount <- 4200
premium_member <- TRUE
if(amount > 5000 | premium_member){
print("Discount Applied")
} else {
print("No Discount")
}

In [ ]:
units <- 250
if(units < 100){
print("Low Usage")
} else if(units <= 300){
print("Medium Usage")
} else {
print("High Usage")
}

In [ ]:
experience <- 6
rating <- 4.5
if(experience > 5 & rating > 4){
print("Bonus Eligible")
} else {
print("Not Eligible for Bonus")
}

In [ ]:
password <- "secure123"
if(nchar(password) >= 8){
print("Valid Password")
} else {
print("Invalid Password")
}

In [ ]:
simple_interest <- function(p, r, t){
si <- (p * r * t) / 100
return(si)
}
simple_interest(10000, 5, 2)

In [ ]:
check_result <- function(marks){
if(marks >= 40){
return("Pass")
} else {
return("Fail")
}
}
check_result(65)

In [ ]:
net_salary <- function(basic_salary){
tax <- basic_salary * 0.10
net <- basic_salary - tax
return(net)
}
net_salary(30000)

In [ ]:
electricity_bill <- function(units){
if(units <= 100){
bill <- units * 2
} else if(units <= 200){
bill <- (100 * 2) + (units - 100) * 3
} else {
bill <- (100 * 2) + (100 * 3) + (units - 200) * 5
}
return(bill)
}
electricity_bill(250)

In [ ]:
final_amount <- function(amount){
if(amount >= 5000){
discount <- amount * 0.20
} else if(amount >= 2000){
discount <- amount * 0.10
} else {
discount <- 0
}
return(amount - discount)
}
final_amount(4500)

In [ ]:
# Student details
students <- data.frame(
RollNo = c(101, 102, 103),
Name = c("Ravi", "Meena", "Karthik"),
Dept = c("CSE", "ECE", "IT")
)
# Student marks
marks <- data.frame(
Marks = c(78, 85, 90)
)
# Join columns
student_data <- cbind(students, marks)
student_data
# Add new student records
new_students <- data.frame(
RollNo = c(104),
Name = c("Anjali"),
Dept = c("CSE"),
Marks = c(88)
)
final_data <- rbind(student_data, new_students)
final_data

  RollNo Name    Dept Marks
1 101    Ravi    CSE  78
2 102    Meena   ECE  85
3 103    Karthik IT   90

  RollNo Name    Dept Marks
1 101    Ravi    CSE  78
2 102    Meena   ECE  85
3 103    Karthik IT   90
4 104    Anjali  CSE  88

In [ ]:
employee_details <- data.frame(
EmpID = c(1, 2, 3),
Name = c("Amit", "Sneha", "Raj"),
Dept = c("HR", "IT", "Finance")
)
salary_details <- data.frame(
Salary = c(35000, 45000, 50000)
)
# Join columns
employees <- cbind(employee_details, salary_details)
employees
# Add new employee
new_employee <- data.frame(
EmpID = 4,
Name = "Neha",
Dept = "IT",
Salary = 48000
)
employees <- rbind(employees, new_employee)
employees

  EmpID Name  Dept    Salary
1 1     Amit  HR      35000
2 2     Sneha IT      45000
3 3     Raj   Finance 50000

  EmpID Name  Dept    Salary
1 1     Amit  HR      35000
2 2     Sneha IT      45000
3 3     Raj   Finance 50000
4 4     Neha  IT      48000

In [ ]:
patient_info <- data.frame(
PatientID = c(201, 202),
Name = c("Suresh", "Lakshmi"),
Age = c(45, 38)
)
treatment_cost <- data.frame(
Cost = c(12000, 15000)
)
# Combine column-wise
patient_records <- cbind(patient_info, treatment_cost)
patient_records
# Add new patient
new_patient <- data.frame(
PatientID = 203,
Name = "Arjun",
Age = 50,
Cost = 18000
)
patient_records <- rbind(patient_records, new_patient)
patient_records

  PatientID Name    Age Cost
1 201       Suresh  45  12000
2 202       Lakshmi 38  15000

  PatientID Name    Age Cost
1 201       Suresh  45  12000
2 202       Lakshmi 38  15000
3 203       Arjun   50  18000

In [ ]:
products <- data.frame(
ProductID = c(1, 2, 3),
ProductName = c("Pen", "Book", "Bag")
)
stock <- data.frame(
Quantity = c(100, 50, 30)
)
# Join columns
inventory <- cbind(products, stock)
inventory
# Add new product
new_product <- data.frame(
ProductID = 4,
ProductName = "Bottle",
Quantity = 75
)
inventory <- rbind(inventory, new_product)
inventory

  ProductID ProductName Quantity
1 1         Pen         100
2 2         Book         50
3 3         Bag          30

  ProductID ProductName Quantity
1 1         Pen         100
2 2         Book         50
3 3         Bag          30
4 4         Bottle       75

In [ ]:
students <- data.frame(
RollNo = c(1, 2, 3),
Name = c("Arun", "Bina", "Charan"),
Dept = c("CSE", "ECE", "IT")
)
# Semester marks
marks <- data.frame(
Sem1 = c(78, 82, 90),
Sem2 = c(80, 85, 88)
)
# Attendance
attendance <- data.frame(
Attendance = c(92, 88, 95)
)
# Combine all columns
student_records <- cbind(students, marks, attendance)
student_records
# New admissions
new_students <- data.frame(
RollNo = c(4, 5),
Name = c("Deepa", "Eshan"),
Dept = c("CSE", "IT"),
Sem1 = c(85, 89),
Sem2 = c(87, 91),
Attendance = c(90, 93)
)
# Add rows
final_records <- rbind(student_records, new_students)
final_records

In [ ]:
students <- data.frame(
RollNo = c(1, 2, 3),
Name = c("Arun", "Bina", "Charan"),
Dept = c("CSE", "ECE", "IT")
)
marks <- data.frame(
RollNo = c(1, 2, 3),
Sem1 = c(78, 82, 90),
Sem2 = c(80, 85, 88)
)
attendance <- data.frame(
RollNo = c(1, 2, 3),
Attendance = c(92, 88, 95)
)
# Merge student details and marks
student_data <- merge(students, marks, by = "RollNo")
# Merge with attendance
final_records <- merge(student_data, attendance, by = "RollNo")
final_records

  RollNo Name   Dept Sem1 Sem2 Attendance
1 1      Arun   CSE  78   80   92
2 2      Bina   ECE  82   85   88
3 3      Charan IT   90   88   95

In [ ]:
patients <- data.frame(
PatientID = c(201, 202, 203),
Name = c("Suresh", "Lakshmi", "Arjun"),
Age = c(45, 38, 52)
)
diagnosis <- data.frame(
PatientID = c(201, 203),
Disease = c("Diabetes", "Cardiac")
)
billing <- data.frame(
PatientID = c(201, 202, 203),
Amount = c(15000, 12000, 25000)
)
# Merge patients with diagnosis
hospital_data <- merge(patients, diagnosis, by = "PatientID", all.x = TRUE)
# Merge with billing
hospital_data <- merge(hospital_data, billing, by = "PatientID")
hospital_data

  PatientID Name    Age Disease  Amount
1 201       Suresh  45  Diabetes 15000
2 202       Lakshmi 38  NA       12000
3 203       Arjun   52  Cardiac  25000

In [ ]:
names <- c("arun", "Bala", "chitra")
upper_names <- toupper(names)
name_length <- nchar(upper_names)
upper_names
name_length

[1] "ARUN"   "BALA"   "CHITRA"

[1] 4 4 6

In [ ]:
emails <- c("arun@gmail.com", "meena@yahoo.com", "ravi@outlook.com")
usernames <- sub("@.*", "", emails)
usernames

In [ ]:
input <- c(" R Programming ", " Data Science ", " AI ")
clean_input <- trimws(input)
clean_input

[1] "R Programming" "Data Science"  "AI"

In [ ]:
product_codes <- c("PRD101", "PRD202", "ABC303")
valid_codes <- startsWith(product_codes, "PRD")
valid_codes

[1]  TRUE  TRUE FALSE

In [ ]:
password <- "secure123"
if(nchar(password) >= 8){
print("Strong Password")
} else {
print("Weak Password")
}

[1] "Strong Password"

In [ ]:
students <- data.frame(
Name = c(" Gayathri ", "RAVI ", " meena"),
Email = c("Gayu@UNIV.edu", "ravi@univ.edu", "meena@gmail.com"),
Department = c(" cse", "ECE ", " Cse ")
)
students
students$Name <- trimws(students$Name)
students$Department <- trimws(students$Department)
students$Name <- toupper(students$Name)
students$Email <- tolower(students$Email)
students$Department <- toupper(students$Department)
students$Username <- sub("@.*", "", students$Email)
students$ValidEmail <- grepl("@univ.edu$", students$Email)
clean_students <- students[students$ValidEmail == TRUE, ]
clean_students

In [ ]:
products <- data.frame(
Product = c(" apple phone ", "SAMSUNG-TV ", " dell laptop"),
Code = c("PRD-101-APL", "PRD-202-SAM", "PRD-303-DEL")
)
products$Product <- trimws(products$Product)
products$Product <- tools::toTitleCase(tolower(products$Product))
products$ProductCode <- sub("PRD-[0-9]+-", "", products$Code)
product

In [ ]:
marks <- c(78, 85, 90, 88, 76)
total <- sum(marks)
average <- mean(marks)
highest <- max(marks)
total
average
highest

In [ ]:
temperature <- c(32, 33, 31, 34, 35, 36, 33)
min_temp <- min(temperature)
max_temp <- max(temperature)
min_temp
 max_temp

In [ ]:
employee <- list(
ID = 101,
Name = "Gayathri",
Salary = 45000,
Department = "IT"
)
employee
employee$Name
employee$Salary

In [ ]:
students <- data.frame(
 RollNo = c(1, 2, 3),
Name = c("Anitha", "Karthik", "Meena"),
Dept = c("CSE", "ECE", "IT"),
Marks = c(85, 78, 92)
)
students

In [ ]:
# Data
 departments <- c("CSE", "ECE", "IT", "Mechanical")
 students <- c(120, 80, 60, 40)
# Pie Chart
 pie(
 students,
 labels = departments,
 main = "Student Enrollment per Department",
 col = c("skyblue", "orange", "green", "pink")
 )
# Bar Chart
 barplot(
 students,
 names.arg = departments,
 main = "Number of Students per Department",
 xlab = "Department",
 ylab = "Number of Students",
 col = c("skyblue", "orange", "green", "pink")
 )

In [ ]:
category <- c("Electronics", "Clothing", "Accessories", "Home Appliances")
sales <- c(150000, 75000, 50000, 25000)
# Pie Chart
pie(
sales,
labels = category,
main = "Sales Distribution by Category",
col = rainbow(length(category))
)
# Bar Chart
barplot(
sales,
names.arg = category,
main = "Sales per Category",
xlab = "Category",
ylab = "Sales (₹
)",
col = rainbow(length(category))
)

In [ ]:
# Step 1: Create dataset
students <- data.frame(
Name =
c("Arjun","Meena","Rahul","Anitha","Kiran","Sneha","Ravi","Gayathri","Suresh","
Maths = c(85,90,70,95,80,88,75,92,68,86),
Science = c(78,88,60,92,85,80,70,90,75,82),
English = c(92,80,75,98,88,85,78,91,80,87)
)
# Step 2: Mean, Median, SD
mean marks <- sapply(students[ ,2:4], mean)